version: "3"
services:
  app:
    container_name: graphqlapp
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongodb
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_ROOTPASS=${MONGO_ROOTPASS}

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOTPASS}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOTPASS}
      - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
volumes:
  data: {}
networks:
  default:
    name: mongodb_network      